-- Retail Sales Analytics using SQL
-- 1. What is the total revenue generated by the company?

-- Business Need: Measure the company's overall sales performance.

SELECT
ROUND(SUM(sales),2) AS total_sales
FROM clean_superstore;

-- 2. What is the total profit earned by the company?

-- Business Need: Determine the company's overall profitability.

SELECT
ROUND(SUM(profit),2) AS total_profit
FROM clean_superstore;

-- 3. How many unique orders were placed?

-- Business Need: Measure the total number of customer orders.

SELECT
COUNT(DISTINCT order_id) AS total_orders
FROM clean_superstore;

-- 4. What is the average order value?

-- Business Need: Understand how much customers spend per order.

SELECT 
ROUND(ROUND(SUM(sales),2)/COUNT(DISTINCT order_id),2)
AS average_order
FROM clean_superstore;

-- 5. What is the average profit margin?

-- Business Need: Evaluate overall business profitability.

SELECT
ROUND(AVG(profit_margin),2) AS average_profit_margin
FROM clean_superstore;

-- 6. Which region generates the highest revenue?

-- Business Need: Identify the strongest-performing sales region.

SELECT
region,
ROUND(SUM(sales),2) AS total_sales
FROM clean_superstore
GROUP BY region
ORDER BY total_sales DESC;


-- 7. Which region generates the highest profit?

-- Business Need: Determine the most profitable region.

SELECT
region,
ROUND(SUM(profit),2) AS total_profit
FROM clean_superstore
GROUP BY region
ORDER BY total_profit DESC
LIMIT 1;


-- 8. Which product category generates the highest sales?

-- Business Need: Identify the category contributing the most revenue.

SELECT
category,
ROUND(SUM(sales),2) AS total_sales
FROM clean_superstore
GROUP BY category
ORDER BY total_sales DESC;

-- 9. Which product category generates the highest profit?

-- Business Need: Find the most profitable product category.

SELECT
category,
ROUND(SUM(profit),2) AS total_profit
FROM clean_superstore
GROUP BY category
ORDER BY total_profit DESC;

-- 10. Which customer segment contributes the most revenue?

-- Business Need: Understand which customer segment is most valuable.

SELECT
segment,
ROUND(SUM(sales),2) AS total_sales
FROM clean_superstore
GROUP BY segment
ORDER BY total_sales DESC;

-- 11. Which shipping mode is used the most?

-- Business Need: Analyze customer shipping preferences.

SELECT ship_mode,COUNT(ship_mode) AS count_of_modes
FROM clean_superstore
GROUP BY ship_mode
ORDER BY count_of_modes DESC;

-- 12. Who are the top 10 customers by sales?

-- Business Need: Identify high-value customers for loyalty programs.

SELECT 
customer_name,
ROUND(SUM(sales),2) AS sales_revenue
FROM clean_superstore
GROUP BY customer_name
ORDER BY  sales_revenue DESC
LIMIT 10;
 
-- 13. Which products generate the highest sales?

-- Business Need: Identify the best-selling products.

SELECT 
product_name,
ROUND(SUM(sales),2) AS sales_revenue
FROM clean_superstore
GROUP BY product_name
ORDER BY  sales_revenue DESC
LIMIT 10;

-- 14. Which products generate the lowest profit?

-- Business Need: Find products that may require pricing or discount optimization.

SELECT 
product_name,
ROUND(SUM(profit),2) AS  total_profit
FROM clean_superstore
GROUP BY product_name
ORDER BY  total_profit ASC
LIMIT 10;

-- 15. Which states generate the highest revenue?

-- Business Need: Identify top-performing states for future expansion.

SELECT
state,
ROUND(SUM(sales),2) AS total_sales
FROM clean_superstore
GROUP BY state
ORDER BY total_sales DESC
LIMIT 5;

-- 16. Which cities generate the highest revenue?

-- Business Need:
-- Identify the top-performing cities to support marketing campaigns and business expansion.

SELECT
    city,
    ROUND(SUM(sales),2) AS total_sales
FROM clean_superstore
GROUP BY city
ORDER BY total_sales DESC
LIMIT 10;

-- 17. How do monthly sales change over time?

-- Business Need:
-- Identify seasonal sales patterns and monthly business performance.

SELECT
    year,
    month_name,
    ROUND(SUM(sales),2) AS total_sales
FROM clean_superstore
GROUP BY year, month, month_name
ORDER BY year, month;

-- 18. How has yearly revenue changed?

-- Business Need:
-- Measure the company's revenue growth over the years.

SELECT
    year,
    ROUND(SUM(sales),2) AS total_sales
FROM clean_superstore
GROUP BY year
ORDER BY year;

-- 19. How has yearly profit changed?

-- Business Need:
-- Evaluate long-term profitability trends.

SELECT
    year,
    ROUND(SUM(profit),2) AS total_profit
FROM clean_superstore
GROUP BY year
ORDER BY year;

-- 20. Which customers have spent more than ₹20,000?

-- Business Need:
-- Identify premium customers for loyalty programs and personalized marketing.

SELECT 
customer_name,
ROUND(SUM(sales),2) AS spendings
FROM clean_superstore
GROUP BY customer_name
HAVING spendings > 20000
ORDER BY spendings DESC;



-- 21. Which products generated more than ₹5,000 profit?

-- Business Need:
-- Identify products that contribute significantly to business profit.

SELECT product_name,
ROUND(SUM(profit),2) AS total_profit
FROM clean_superstore
GROUP BY product_name
HAVING  total_profit > 5000
ORDER BY  total_profit DESC;


-- 22. Rank customers based on total sales.

-- Business Need:
-- Identify the highest-value customers using rankings.

SELECT 
	   customer_name,
        ROUND(SUM(sales),2) AS Total_Sales,
       DENSE_RANK() OVER (ORDER BY SUM(sales) DESC)AS Customer_rank
FROM clean_superstore
GROUP BY customer_name;

-- 23. Rank products based on profit.

-- Business Need:
-- Identify the most profitable products using ranking.

SELECT
    product_name,
    ROUND(SUM(profit),2) AS total_profit,
    DENSE_RANK() OVER(ORDER BY SUM(profit) DESC) AS product_rank
FROM clean_superstore
GROUP BY product_name;


-- 24. What is the running total of sales over time?

-- Business Need:
-- Track cumulative sales growth throughout the business period.

SELECT
    order_date,
    sales,
    SUM(sales)
    OVER(ORDER BY order_date) AS running_total
FROM clean_superstore;


-- 25. What is the 7-day moving average of sales?

-- Business Need:
-- Smooth daily sales fluctuations to identify trends.

SELECT
    order_date,
    sales,
    AVG(sales)
    OVER(
        ORDER BY order_date
        ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
    ) AS moving_average
FROM clean_superstore;


-- 26. Which region generates the highest revenue? (Using CTE)

-- Business Need:
-- Demonstrate the use of a Common Table Expression (CTE) for cleaner and more readable SQL.


WITH region_sales AS
(
    SELECT
        region,
        SUM(sales) AS total_sales
    FROM clean_superstore
    GROUP BY region
)

SELECT *
FROM region_sales
ORDER BY total_sales DESC;


-- 27. Which customers spend more than the average customer?

-- Business Need:
-- Identify customers whose total spending exceeds the average customer spending.

WITH customer_sales AS
(
    SELECT
        customer_name,
        SUM(sales) AS total_sales
    FROM clean_superstore
    GROUP BY customer_name
)

SELECT *
FROM customer_sales
WHERE total_sales >
(
    SELECT AVG(total_sales)
    FROM customer_sales
);

-- 28. Who is the top customer in each region?

-- Business Need:
-- Identify the highest-value customer within every region.

WITH ranked_customers AS
(
    SELECT
        customer_name,
        region,
        ROUND(SUM(sales),2) AS total_sales,
        DENSE_RANK() OVER (PARTITION BY region
							ORDER BY SUM(sales) DESC) AS customer_rank
    FROM clean_superstore
    GROUP BY region, customer_name
)

SELECT customer_name,
		region,
        total_sales
FROM ranked_customers
WHERE customer_rank = 1;

-- 29. Which product is the most profitable in each category?

-- Business Need:
-- Identify the flagship product for each product category.

WITH ranked_products AS
(
    SELECT
        category,
        product_name,
        ROUND(SUM(profit),2) AS total_profit,
        DENSE_RANK() OVER (PARTITION BY category
							ORDER BY SUM(profit) DESC) AS product_rank
    FROM clean_superstore
    GROUP BY category, product_name
)

SELECT category,
		product_name,
        total_profit
FROM ranked_products
WHERE product_rank = 1;

-- 30. What percentage of total revenue is contributed by each region?

-- Business Need:
-- Understand each region's contribution to overall company revenue.

SELECT region,
		ROUND(SUM(sales)* 100 / (SELECT SUM(sales) FROM clean_superstore),2) AS sales_percent
        FROM clean_superstore
        GROUP BY region;





